
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CID CONSULTA CPF DATA DOSAGEM MEDICAMENTO PACIENTE STRINGregistro : PACIENTE STRING CPF STRING CONSULTA DATA STRING CID STRING MEDICAMENTO STRING DOSAGEM STRING'
    
_lr_action_items = {'PACIENTE':([0,],[2,]),'$end':([1,14,],[0,-1,]),'STRING':([2,4,7,9,11,13,],[3,5,8,10,12,14,]),'CPF':([3,],[4,]),'CONSULTA':([5,],[6,]),'DATA':([6,],[7,]),'CID':([8,],[9,]),'MEDICAMENTO':([10,],[11,]),'DOSAGEM':([12,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'registro':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> registro","S'",1,None,None,None),
  ('registro -> PACIENTE STRING CPF STRING CONSULTA DATA STRING CID STRING MEDICAMENTO STRING DOSAGEM STRING','registro',13,'p_registro','parser.py',7),
]
